### ISSUE TITLE
Bug: auth 登录后不刷新页面，status显示错误

### ISSUE THREAD

**Issue by mengshouer** [koishijs/console#105]
发现字段问题已经有issue了(改个issue

![image](https://user-images.githubusercontent.com/36481080/219928463-4c6a86f8-a16e-4e54-bed3-204302ec8f56.png)

**Comment by shigma** [comment]
这个问题是什么，跟 #100 是同一个吗？

**Comment by mengshouer** [comment]
倒不会重复显示，只是从没开启到开启auth的时候在没刷新浏览器之前，底部显示会有问题，左下角有版本号，但是移上去没有tooltip，然后右下角没有状态，刷新浏览器就能好。

**Comment by mengshouer** [comment]
复现方法，开启 auth ，刷新浏览器，登录，下面就是这样

**Comment by shigma** [comment]
这个 bug 应该修过，看看现在还有吗？

**Comment by mengshouer** [comment]
已解决
