### ISSUE TITLE
Bug: 分组收起需要点击两次

### ISSUE THREAD

**Issue by CN-traveler** [koishijs/console#108]
### Describe the bug

分组收起需要点击两次

### Steps to reproduce

分组收起需要点击两次

### Expected behavior

点击一次就可以收起

### Screenshots

![image](https://user-images.githubusercontent.com/55753029/220655732-d915b6f7-c579-40e8-90d9-5d93ae10bf14.png)

### Versions

- Koishi version: latest

**Comment by shigma** [comment]
研究了半天，感觉是 element-plus 的问题……

**Comment by shigma** [comment]
研究了半天，现在能修了
