### ISSUE TITLE
Bug: 状态栏从2个变成0个

### ISSUE THREAD

**Issue by medicago087** [koishijs/console#109]
![image](https://user-images.githubusercontent.com/68104673/220831648-ff0ebfef-54ce-4f8f-bd42-c773a777ceab.png)
在一次bot的自然死亡后，状态栏自然的从2个变成了0个，比2个致命，无报错信息，等有缘人复现（

**Comment by shigma** [comment]
此问题现在还可复现吗？

**Comment by medicago087** [comment]
![image](https://user-images.githubusercontent.com/68104673/226254796-1f900526-d942-4f1d-a171-2bdf90346870.png)
很安定的什么都没有，并且当我开多实例的时候，default会变成default2的形状，完全没有头猪

**Comment by shigma** [comment]
看下 F12?

**Comment by medicago087** [comment]
![image](https://user-images.githubusercontent.com/68104673/226256460-ec2d0640-a2a2-4fd0-9e36-bf5338b92874.png)

**Comment by medicago087** [comment]
我是猪
