### ISSUE TITLE
@koishijs/plugin-market 1.12.0 插件过滤器设置失效

### ISSUE THREAD

**Issue by Zhuager** [koishijs/console#117]
@koishijs/plugin-market插件由1.11.4升级至1.12.0版本后，在插件配置页面，插件的过滤器配置不可用，而分组的过滤器设置可用。
回退至1.11.4版本后问题消失，插件及分组的过滤器设置均可用。

**Comment by shigma** [comment]
感谢反馈！问题已定位，会尽快修复。
