### ISSUE TITLE
Bug: 一些子指令未在「插件配置」和「指令管理」中绑定

### ISSUE THREAD

**Issue by ilharp** [koishijs/console#123]
### Describe the bug

一些子指令未在「插件配置」和「指令管理」中绑定，如 dialogue 插件和 teach 指令。

### Steps to reproduce

安装 dialogue 插件，观察到插件和 teach 指令之间无法相互跳转。

### Expected behavior

指令实现跳转。

### Screenshots

![image](https://user-images.githubusercontent.com/20179549/223219221-d38f8009-a79c-4f12-93fa-44c640273367.png)

### Versions

```txt
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

Binaries:
    Node: 16.17.0
    Yarn: 3.2.3

Koishi:
    Core: 4.11.9
    Console: 5.5.3
    Koishi Desktop: 0.9.2
```

**Comment by shigma** [comment]
请问你还观察到其他类似的指令吗？这可能是由于插件开发不当导致的。

**Comment by shigma** [comment]
<img width="375" alt="image" src="https://user-images.githubusercontent.com/33423008/224007538-8f299c37-3ecc-41dc-b36c-1bc0e0ff9375.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/33423008/224007573-5cc6d72b-9ad5-4242-8aaf-0b03986b87b0.png">

应该是不止这些的。

**Comment by shigma** [comment]
已经发现共性：只要指令不是在插件顶层注册就会有此问题。

**Comment by ilharp** [comment]
![image](https://user-images.githubusercontent.com/20179549/224083854-e5b2c122-9cc4-4f2a-b238-4266b1517147.png)

小吐槽：我这里 usage 是正常的，神奇

**Comment by shigma** [comment]
4.12.0 更新了 usage，然后它就不在插件顶层上下文了。
