### ISSUE TITLE
Bug: auth 插件失效

### ISSUE THREAD

**Issue by lgc2333** [koishijs/console#128]
报错如下
![Screenshot_20230315-214259](https://user-images.githubusercontent.com/59048777/225329830-cf7bc439-ddaa-459b-9862-f0dedaa628a6.png)

当删掉数据库user表中对应的一项后重启koishi，问题可以暂时解除

**Comment by shigma** [comment]
已定位该问题。我们将尽快修复。感谢你的反馈。
