### ISSUE TITLE
插件市场中添加插件显示不兼容

### ISSUE THREAD

**Issue by Anillc** [koishijs/console#27]
显然应该是兼容的

![image](https://user-images.githubusercontent.com/23411248/182040135-79f3efa1-c4f7-4e08-9d56-e8e816d2be67.png)

**Comment by shigma** [comment]
问题定位：构建生成了以下代码，然后此处 `Comparator$3` 为 undefined，导致构造 `Range$a` 失败。应该是与构建相关的问题。

![image](https://user-images.githubusercontent.com/33423008/182040213-b77e813e-91c0-4bdd-8869-600eed127a2e.png)

**Comment by shigma** [comment]
最新版已修复。
