### ISSUE TITLE
Bug: devMode 开启后控制台报错

### ISSUE THREAD

**Issue by brokenpoems** [koishijs/console#32]
### Describe the bug

rt,且yarn start可以

### Steps to reproduce

使用最新的模版创建koishi bot,使用yarn dev启动

### Expected behavior

正常打开控制台

### Screenshots

koishi日志无异常,浏览器控制台
![001](https://user-images.githubusercontent.com/60998827/191958856-eed9e863-4be0-44b9-8f14-78a1628155bb.png)
![002](https://user-images.githubusercontent.com/60998827/191958864-11944942-4849-4431-b657-f94d17e7e81c.png)

### Versions

- OS: Windows 10 
- Platform: NONE
- Node version: v16.16.0
- Koishi version: 4.9.2

**Comment by shigma** [comment]
临时解决方案：删除 koishi.yml 中的 `devMode: true` 一行。删除后控制台插件将无法正常 dev，但是控制台本身能够正常显示，且 dev 各项功能仍然正常运行。目前模板项目已经修改。

**Comment by brokenpoems** [comment]
使用的是 yarn 1.22.19

**Comment by Seidko** [comment]
我通过npm run dev出现的这个问题
复现流程：
1. npm init koishi
2. npm run start
3. 按照正常流程配置koishi
4. 创建plugins文件夹并编写插件
5. npm run dev ，出现此错误

**Comment by brokenpoems** [comment]
我通过yarn dev出现的这个问题
复现流程：
1. yarn
2. yarn dev,出现此错误
这个是我复制之后的[模板库](https://github.com/brokenpoems/cm)

**Comment by brokenpoems** [comment]
![001](https://user-images.githubusercontent.com/60998827/192107157-5050eeb9-1e7d-4676-9135-80f92030e76e.png)
 复现过程

**Comment by shigma** [comment]
先用上面的临时解决方案吧，我暂时没啥头绪了
