### ISSUE TITLE
Bug: 通过yarn dev启动的console插件配置无法加载

### ISSUE THREAD

**Issue by Seidko** [koishijs/console#34]
## Describe the bug
**情况如图：**
![image](https://user-images.githubusercontent.com/64234553/194264258-5a4d038b-f6f1-436e-8fed-2e9e4fd0b68c.png)

通过`yarn dev`启动的console中插件设置打开的时候无内容加载。

引用：#32 

## Steps to reproduce

1. `yarn create koishi`创建项目
2. `yarn dev`启动项目
3. 点开控制台插件设置，然后点击任意一个插件，控制台就能出现如上报错

## Expected behavior
插件配置行为与`yarn start`相同

## Screenshots

<details>
  <summary>报错内容</summary>

   ![image](https://user-images.githubusercontent.com/64234553/194265508-9ff5bff0-8431-4d16-9a15-7dc0a3093c5f.png)
   ![image](https://user-images.githubusercontent.com/64234553/194268273-8f2adf83-a32d-41c5-ad7f-ed5df505badb.png)

</details>

## Versions
- OS: Windows 10 21H2
- Platform: x86_64
- Node version: v16.17.0
- Koishi version: v4.9.4

**Comment by shigma** [comment]
此问题现在仍然存在吗？

**Comment by Seidko** [comment]
已修复，感谢！
