### ISSUE TITLE
Feature: 加个日志的自动滚动功能吧，日志等级筛选也行啊

### ISSUE THREAD

**Issue by MXDexRazero** [koishijs/console#42]
### Describe the problem related to the feature request

![image](https://user-images.githubusercontent.com/112014237/196034409-8a60b1ff-fe14-45c8-838e-1916543bb3be.png)
查看日志需要手动向下滚动屏幕，而且是刷新一次滚动到底一次，挺不方便的，或者有新消息时也不能及时看见新消息。

### Describe the solution you'd like

加入日志的自动滚动功能。

### Describe alternatives you've considered

每次刷新显示最新一行日志。

### Additional context

谢谢你

**Comment by shigma** [comment]
自动滚动问题已经解决。等级筛选如果想要的话麻烦你再开一个 issue。感谢反馈。
