### ISSUE TITLE
Feature: sanbox输入框加入按上下方向键获取历史发送内容的功能

### ISSUE THREAD

**Issue by Lipraty** [koishijs/console#43]
在开发时会经常在sandbox重复输入某一个命令或内容以测试机器人功能，如能像terminal那样按上下方向键得到历史发送的内容，这样开发就更方便快捷了（

**Comment by shigma** [comment]
已实现此功能，请更新 sandbox 到 2.6.1，console 到 5.1.14 以上版本。

（目前似乎有一个小问题，就是按下方向键后，光标会被锁定在输入框左侧而不是文本右侧。暂时不知道如何解决。）

**Comment by Lipraty** [comment]
好耶！已使用！

> （目前似乎有一个小问题，就是按下方向键后，光标会被锁定在输入框左侧而不是文本右侧。暂时不知道如何解决。）

对于光标是否可以使用例如 `input.setSelectionRange(0, 0, 'backward')` 来将光标强制设置到最后？

**Comment by HuanLinOTO** [comment]
我也有个小问题 就是上下文快捷这个功能会不会导致多行文本编辑时被干掉

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by shigma** [comment]
> 我也有个小问题 就是上下文快捷这个功能会不会导致多行文本编辑时被干掉

你可以复现试试。
