### ISSUE TITLE
Bug: cannot search plugin in market

### ISSUE THREAD

**Issue by yunkuangao** [koishijs/console#44]
### Describe the bug

I write a plugin and publish to [npm repo](https://www.npmjs.com/package/koishi-plugin-gameserver),
and I cannot search now in koishi [market](https://koishi.js.org/market.html) or my koishi console.
But I was able to find it in the market before and it has been enabled in my console.

### Steps to reproduce

search gameserver or yunkuangao in koishi market 

### Expected behavior

I want to find my plugin in market

### Screenshots

this is koishi market:
![image](https://user-images.githubusercontent.com/40163747/199397618-958e2818-95b0-4c08-996b-50f5b5bc64e6.png)

and this is my console:
![image](https://user-images.githubusercontent.com/40163747/199397860-77bdb54b-909e-44f8-b631-61c7fd695130.png)

this is my plugin:
![image](https://user-images.githubusercontent.com/40163747/199398824-0d426b64-0d7c-4dff-861b-95c7c48de943.png)

### Versions

- OS: docker image koishijs/koishi
- Platform: all
- Node version: 16.18.0
- Koishi version: 4.9.9

**Comment by yunkuangao** [comment]
No,the last publish is 4 days ago.
I try to update endpoint to https://registry.npmjs.org/,but market not change.

**Comment by MaikoTan** [comment]
> No,the last publish is 4 days ago. I try to update endpoint to [registry.npmjs.org/,but](https://registry.npmjs.org/,but) market not change.

Then I think you might lacked some requirement, like:

- a proper name includes `koishi-plugin-*`
- list koishi version in `peerDependencies` in `package.json`
- if there is a field named `koishi` in `package.json` you should not include `hidden: true`

------

那么我想你可能缺少一些要求，比如。

- 一个合适的名字包括`koishi-plugin-*`。
- 在`package.json`中的`peerDependencies`中列出koishi版本。
- 如果在`package.json`中有一个名为`koishi`的字段，你不应该包括`hidden: true`。

**Comment by MaikoTan** [comment]
If you are using the workspace created by `yarn create koishi`, then when you run `yarn setup <plugin-name>`, the script would create a plugin that meets all the requirement for you.

------

如果你使用 `yarn create koishi` 创建的工作空间，那么当你运行 `yarn setup <plugin-name>` 时，该脚本将为你创建一个符合所有要求的插件。

**Comment by MaikoTan** [comment]
If you are using the workspace created by `yarn create koishi`, then when you run `yarn setup <plugin-name>`, the script would create a plugin that meets all the requirement for you.

------

如果你使用 `yarn create koishi` 创建的工作空间，那么当你运行 `yarn setup <plugin-name>` 时，该脚本将为你创建一个符合所有要求的插件。

**Comment by yunkuangao** [comment]
Yes,I use yarn setup,and I published to npm repo.
Even I downloaded it on the market a few days ago.
The amazing thing is that it disappeared when I came to search today.
This is my koishi console, you can see this screenshot.
![image](https://user-images.githubusercontent.com/40163747/199407497-d14e4bb6-314f-482c-a390-eac621033753.png)
And this is my code repo:  https://github.com/yunkuangao/gameserver/blob/master/package.json
you could check it.
Thanks your help.

**Comment by yunkuangao** [comment]
I find this action https://github.com/koishijs/registry/actions/runs/3352522771/jobs/5554719895
The Deploy vercel hava output this url https://koishi-registry-ql3mb4um4-koishi.vercel.app/
I find my publish info:
![image](https://user-images.githubusercontent.com/40163747/199409185-aaec943d-0a59-4049-910b-6f9b19bc1b8c.png)
So maybe other wrong?

**Comment by MaikoTan** [comment]
I would continue digging with this problem, thanks for pointing out!

**Comment by shigma** [comment]
I think this may be a bug of https://github.com/koishijs/registry.

**Comment by yunkuangao** [comment]
OK,I close this issue and report to https://github.com/koishijs/registry/issues/1

**Comment by MaikoTan** [comment]
Actually Shigma and me could transfer this issue from here to `registry` repository, since you created a new one, I would not do such, just an FYI.

其实Shigma和我可以传送这个议题到`注册表`仓库，自从你建立了一个新的，我不会这么做，仅供参考。

**Comment by yunkuangao** [comment]
OK,Thanks again for your help.
