### ISSUE TITLE
Bug: 全局设置中部分开关不显示

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/console#61]
![{6MS14SCH(~J 6EZ`DTS KJ](https://user-images.githubusercontent.com/21092951/210172160-3e89ac8e-2f9c-401d-86d0-2941f1e05c82.png)
如图，这是一个刚刚使用 yarn create 全新安装的实例

**Comment by shigma** [comment]
fixed by shigma/schemastery@dea97712eaef60f116394d56bee567d458f467fd
