### ISSUE TITLE
Feat: 在插件配置页显示插件信息

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/console#66]
目前为止讨论的结果：

1. 插件导出的插件描述
2. 插件作者和插件首页和 npmjs 页的按钮

**Comment by shigma** [comment]
插件作者跟 2 是一类的吧……都是从 registry 去读信息。

1 的插件描述是插件自身导出的 description，不是 readme 或者 package.json 中的 description。

**Comment by H4M5TER** [comment]
插件自身导出的 description 不就可以说是插件作者可选的插件描述嘛

**Comment by shigma** [comment]
抱歉，脑子糊涂了，看成插件作者「和」可选的插件描述了。我的。

**Comment by shigma** [comment]
c7ee29dd6065573c12958cb417849f04e671b43f 实现了 usage。

讲道理我觉得这种 issue 挺不负责任的。开头就是一句「目前为止讨论的结果」，我也不知道是跟谁讨论的。我做了一半，剩下一半不想做了，我也不知道是该写在 commit 里关掉还是不写。

**Comment by shigma** [comment]
如果懒得说可以直接 123 讲需求，老是谜语人别人看不懂也不会来提 issue 了。

**Comment by HuanLinMaster** [comment]
题外话:
issue id: 66

**Comment by Seidko** [comment]
shigma looks a bit angry 😂, I'll take care of the rest of the content. thank you all for your hard work!

**Comment by MirrorCY** [comment]
我来翻译一下
谢谢你，Shigma！
