### ISSUE TITLE
Bug: 沙盒可以显示MP4等视频吗

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/console#71]
### Describe the bug

沙盒里面无法显示MP4视频
![image](https://user-images.githubusercontent.com/113200130/211064850-394ec5bf-34b0-4707-8d51-dc4739c7fd48.png)

### Steps to reproduce

url为本地绝对路径，这样写有问题吗
`
this.session.send(segment.video( url)
`

### Expected behavior

沙盒能显示视频

### Screenshots

估计和图片那个问题一样，前面加了域名
![image](https://user-images.githubusercontent.com/113200130/211065117-ad082b02-ce98-44cd-ac83-63b99c0bd9f5.png)
在新标签打开链接
![image](https://user-images.githubusercontent.com/113200130/211065172-d3b11718-54a2-4c97-874b-caeff38fcb34.png)

### Versions

- OS: Windows 10 
- Platform: sanbox
- Node version:  18.9.0
- Koishi version:  4.10.10

**Comment by shigma** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/33423008/211066841-20b3673e-d032-437f-86cf-15ef2ae5b5d4.png">

这部分逻辑只解决了图片，没有解决视频和音频的问题。

PS：由于视频可能会比较大，这里改成本地代理会更好。

**Comment by idanran** [comment]
> <img alt="image" width="1018" src="https://user-images.githubusercontent.com/33423008/211066841-20b3673e-d032-437f-86cf-15ef2ae5b5d4.png">
> 
> 这部分逻辑只解决了图片，没有解决视频和音频的问题。
> 
> PS：由于视频可能会比较大，这里改成本地代理会更好。

在地址前加个`file:///`不就行了嘛

```
file:///C:/Users/00000/x/test.mp4
```

**Comment by ilharp** [comment]
> 在地址前加个`file:///`不就行了嘛
> 
> ```
> file:///C:/Users/00000/x/test.mp4
> ```

浏览器不支持在非 `file` 协议页面使用 `file` 协议。

**Comment by idanran** [comment]
> > 在地址前加个`file:///`不就行了嘛
> > ```
> > file:///C:/Users/00000/x/test.mp4
> > ```
> 
> 浏览器不支持在非 `file` 协议页面使用 `file` 协议。

原来如此

**Comment by idanran** [comment]
https://github.com/ipfs/js-ipfs

不知道这个有没有用

**Comment by ilharp** [comment]
> [ipfs/js-ipfs](https://github.com/ipfs/js-ipfs)

ipfs 对于普通用户的主要作用是可以把任意文件公开上传网络永久保存，并可在任意位置访问特定文件。不清楚此项目与本 issue 有何联系。

**Comment by idanran** [comment]
> > [ipfs/js-ipfs](https://github.com/ipfs/js-ipfs)
> 
> ipfs 对于普通用户的主要作用是可以把任意文件公开上传网络永久保存，并可在任意位置访问特定文件。不清楚此项目与本 issue 有何联系。

如果能私有的话，应该能当作代理使用。

**Comment by ilharp** [comment]
直接在 Koishi 的内置服务 `ctx.router` 上创建类似 <https://github.com/koajs/static> 的静态文件服务路由即可完成对本地文件的代理。本 issue 并非技术无法实现或需要调研，只是尚没有人来做罢了。

**Comment by idanran** [comment]
> 直接在 Koishi 的内置服务 `ctx.router` 上创建类似 <https://github.com/koajs/static> 的静态文件服务路由即可完成对本地文件的代理。本 issue 并非技术无法实现或需要调研，只是尚没有人来做罢了。
> 

啊这

**Comment by MaikoTan** [comment]
Also there are plugins like [assets-local](https://assets.koishi.chat/plugins/local.html) that has already implemented such feature, what we need to do is just add one into the `sandbox` plugin.

并且那里有插件像[assets-local](https://assets.koishi.chat/plugins/local.html)已经实现了这个功能，我们需要做的仅仅是添加一个到`沙盒`插件。

**Comment by shigma** [comment]
别急，会做的。

**Comment by shigma** [comment]
一些关于此问题的考虑：

1. 为什么不用 base64 直接发送？
因为视频基本上必然超过 WebSocket 和 localStorage 的体积限制。
2. 为什么不用代理方案？
因为图片和视频链接是直接下载的，不走鉴权。这意味着提供了直接访问主机上任意文件的接口。
3. 用 assets 实现会有什么问题？
    - 普遍使用的方案是零配置的 assets-local，此时不会转换 `file:` 协议，导致浏览器仍然无法访问；
    - assets 的定位是转存文件以备长时间使用，目前没有 expire 机制；将其用于 sandbox 后可能会占用使用沙盒界面来调试的人的硬盘空间 (但目前也有一些用户直接 sandbox 用于生产目的)

综上所述，尽管 assets 方案也有缺陷，但目前仍然考虑使用 assets 来解决此问题。使用 assets-local 的用户请注意将自己的 `selfUrl` 配置为 `host:port` 的格式。

**Comment by shigma** [comment]
> 使用 assets-local 的用户请注意将自己的 selfUrl 配置为 host:port 的格式

最新版已支持使用上述方法解决。
