### ISSUE TITLE
Bug: 插件市场「显示已下载的插件」有歧义

### ISSUE THREAD

**Issue by ilharp** [koishijs/console#75]
### Describe the bug

插件市场「显示已下载的插件」有歧义

### Steps to reproduce

![image](https://user-images.githubusercontent.com/20179549/211650991-b9c77134-878f-40a4-84ce-e259d8416987.png)

默认无搜索情况下，我点击「显示已下载的插件（共 33 个）」就会期望他给我显示出这 33 个已下载的插件来，实际上他只是在全部插件里包含了这些插件，并不是只显示了已下载的插件，也没有把已下载的插件放最前面

这总不能说「大家都觉得没问题」了吧，这一看就不合理吧

### Expected behavior

改成「包含已下载的插件」

### Versions

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz

Binaries:
    Node: 16.17.0
    Yarn: 3.2.3

Koishi:
    Core: 4.11.1
    Console: 5.1.1
    Koishi Desktop: 0.9.2

**Comment by shigma** [comment]
倾向于不改。关于上面提议的两个改法均认为无必要：

- 「包含已下载的插件」：显示和隐藏是动作术语，包含是状态术语。在 UI 中普遍使用显示和隐藏而不常用包含。
- 「隐藏已下载的插件」：这个可以接受，但显示和隐藏是一对反义词，如果隐藏可以那么显示也可以。目前的数据会保存在 localStorage 中，要修改这个行为要么增加本不必要的翻转逻辑，要么需要破坏已有的用户数据。

> 这总不能说「大家都觉得没问题」了吧，这一看就不合理吧

确实得看大家的意思。鉴于修改成本较低，如果有很多人在此 issue 下 vote，那么即便有上述理由仍然可以改。为此可以暂留此 issue 处于 open 状态一段时间。

**Comment by idanran** [comment]
显示包含已下载的插件（
