### ISSUE TITLE
Bug: 点击插件市场中的发布者头像，此时自动输入的不是 `email:` 而是 `user:`

### ISSUE THREAD

**Issue by Seidko** [koishijs/console#78]
## Describe the bug
点击插件市场中的插件发布者头像，此时自动输入的不是 `email:` 而是 `user:`，这将导致搜索不出任何结果。

## Steps to reproduce
进入插件市场，点击插件市场中的插件发布者头像，例如 `help` 插件，此时搜索栏自动输入的是 `user:Shigma`

## Expected behavior
点击插件市场中的插件发布者头像，此时搜索栏自动输入的应该是 `email:foo@bar.com`

## Screenshots
点击头像后的插件市场：
![image](https://user-images.githubusercontent.com/64234553/212046999-f62495d6-76d5-44af-9063-abc03e595843.png)

## Versions
System:
OS: Linux 6.1.4-arch1-1
CPU: Intel (R) Core(TM) Processor i3-3240

## Binaries:
Node: v19.4.0
Yarn: 1.22.19

## Koishi:
Core: 4.11.1
Console: 5.1.5

**Comment by shigma** [comment]
已修复。
