### ISSUE TITLE
Bug: 如果插件扩展 user 表字段并写入内容后，则无法通过 dataview 进行编辑、删除数据。

### ISSUE THREAD

**Issue by Lipraty** [koishijs/console#83]
### Describe the bug

> 目前仅在 SQLite 中测试验证
> dev/prod 模式均存在问题
> 插件扩展的新表未受影响

由插件扩展 user 表字段并写入内容后，打开 dataview 页面编辑或删除数据后，返回修改成功，但实际未修改。但是可以添加一行新的数据。

### Steps to reproduce

插件在根据文档步骤扩展 user 表字段后，添加数据。

打开 dataview 编辑或删除任意数据。

### Expected behavior

数据能够通过 Dataview 正确的删改。

### Screenshots

修改过程如下：

![2023011401](https://user-images.githubusercontent.com/18106422/212529157-d5e44ed0-511e-4c44-a01c-01db6683ebd1.gif)

控制台无输出，无报错，因此未截图。

### Versions

- OS: Debian 11
- Node version: 19.3.0
- Koishi version: 4.11.1

**Comment by nmMmnmMmn** [comment]
本地未能复现该问题。是否可能存在其他程序占用数据库db文件导致无法写入？

![image](https://user-images.githubusercontent.com/21982381/213603824-74e709da-1740-4473-9a18-56caa2c5c0b5.png)

https://user-images.githubusercontent.com/21982381/213603786-be272f88-af6c-4083-8a55-1e45356c53cb.mp4

**Comment by Lipraty** [comment]
> 本地未能复现该问题。是否可能存在其他程序占用数据库db文件导致无法写入？

已确认过不是占用问题，要不试着在 adTest 字段中写入数据？

（我目前在用户群内看见的有约 4 位用户遇到了同样的情况。根据之前梦梦的猜测可能是缓存问题，我年后找个时间看看是否是 sqlite 独有的问题。）

**Comment by nmMmnmMmn** [comment]
> > 本地未能复现该问题。是否可能存在其他程序占用数据库db文件导致无法写入？
> 
> 已确认过不是占用问题，要不试着在 adTest 字段中写入数据？
> 
> （我目前在用户群内看见的有约 4 位用户遇到了同样的情况。根据之前梦梦的猜测可能是缓存问题，我年后找个时间看看是否是 sqlite 独有的问题。）

那就不得而知了，我这边同样是sqlite，改哪个字段都没问题，包括插件扩展的 adTest 字段。

**Comment by ifrvn** [comment]
经测，当扩展的字段为 `list` 类型且值为空时会稳定复现此问题。

在dataview上修改该字段也会报错。

```typescript
import { Context, Logger, Schema, Session } from 'koishi'

declare module 'koishi' {
  interface User {
    test1: string
    test2: string[]
    test3: number
  }
}

export interface Config {}

export default class AdPlugin {
  static using = ['database', 'logger'] as const
  private readonly logger: Logger
  static Config = Schema.object({})

  constructor(private readonly ctx: Context, private readonly config: Config) {
    this.logger = ctx.logger('TestPlugin')

    ctx.model.extend('user', {
      test1: 'string',
      test2: 'list', // 或者 { type: 'list', initial: [] }
      test3: { type: 'integer', initial: 0 }
    })

    ctx.middleware(async (session: Session<'id' | 'test1' | 'test2' | 'test3'>, next) => {
      const content = session.content
      if (['test', '测试'].includes(content) && (session.user != null)) {
        this.logger.debug(content)
        session.user.test1 = new Date().toISOString()
        session.user.test2.push('foo')
        session.user.test3++
        await session.send(content)
      }
      return next()
    })
  }

}
```


https://user-images.githubusercontent.com/21982381/216616850-1c0abf4c-5bd5-48ba-82d2-c0e3918d58be.mp4

**Comment by shigma** [comment]
此问题已修复，分别在 dataview@2.2.1 和 database-sqlite@3.2.5 完成。

**Comment by Lipraty** [comment]
好耶🚀
