### ISSUE TITLE
Feature: 自动更新插件市场

### ISSUE THREAD

**Issue by shigma** [koishijs/console#88]
建议更新间隔保持在 12 小时以上，以免造成对服务器的攻击。

**Comment by HuanLinMaster** [comment]
这次的 issue 指的是「Github Action 对于 NPM 的 Koishi 插件的检索」还是「在 console 的插件市场 tab 中的插件市场刷新」呢

**Comment by HuanLinMaster** [comment]
谢谢你, Shigma

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by shigma** [comment]
这么设计的话时间确实可以短一点了，比如 6h（未来也可以考虑配置）。

**Comment by shigma** [comment]
现在改成当检测到新的连接时，如果超过 12h 就自动更新了。
