### ISSUE TITLE
Bug: 未发布至npm的插件无法打开对应的插件配置页面

### ISSUE THREAD

**Issue by nmMmnmMmn** [koishijs/console#90]
## 问题描述

自己写的插件没发布到npm，打开插件的配置页就炸了

![image](https://user-images.githubusercontent.com/21982381/214598978-36b276b6-2f03-45d0-943b-c2fcc44c6d3b.png)

![image](https://user-images.githubusercontent.com/21982381/214598707-3e7f01bf-fce4-4d50-8a63-da6ec380ad41.png)

对应的是这一行，上面的调试信息可以看到`dep.versions`为undefined

https://github.com/koishijs/console/blob/2f95734319a40fd9459b4f77f63b3891400ccdb4/packages/market/client/settings/plugin.vue#L21

## 复现步骤

新建一个插件，打开控制台，在【插件配置】中点击对应插件

## 版本信息

当前market版本为1.8.13，回退到1.8.9后正常

**Comment by shigma** [comment]
感谢您的反馈！1.8.14 应该已修复此问题。
