### ISSUE TITLE
Bug: 控制台保存默认配置不会被写入koishi.yml，导致无法启用插件

### ISSUE THREAD

**Issue by nmMmnmMmn** [koishijs/console#92]
如果配置项中存在required的配置且带有default，在控制台页面看来没有问题，但无法启用插件

![image](https://user-images.githubusercontent.com/21982381/214757994-32c3a353-bdb0-4a18-8c51-15c084221769.png)

![image](https://user-images.githubusercontent.com/21982381/214758147-2c06d27a-a4d8-44da-a5b2-a1ecfa1ce3ec.png)

原因是koishi.yml文件中没有添加这个配置项

![image](https://user-images.githubusercontent.com/21982381/214758320-8bc4a2f9-d605-4b68-84ba-a128cad96e0b.png)

需要手动将配置写入koishi.yml，或是在控制台更改配置，保存配置，配置才能被写入到koishi.yml中，才能开启插件

![image](https://user-images.githubusercontent.com/21982381/214758657-f83d9e92-533a-4669-8cf3-d59e88838d72.png)

**Comment by shigma** [comment]
这是插件自己的问题，有 default 的不能标 required

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
